# {{templateWarning}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-repository-ha-operator-certified
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-repository-ha-operator-certified
  template:
    metadata:
      labels:
        name: nexus-repository-ha-operator-certified
    spec:
      serviceAccountName: nexus-repository-ha-operator-certified
      containers:
        - name: nexus-repository-ha-operator-certified
          # Replace this with the built image name
          image: {{operatorSHA}}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nexus-repository-ha-operator-certified"
            - name: RELATED_IMAGE_NEXUS
              value: {{certAppSHA}}