# {{templateWarning}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-repository-ha-operator-certified
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-repository-ha-operator-certified
  template:
    metadata:
      labels:
        name: nexus-repository-ha-operator-certified
    spec:
      serviceAccountName: nexus-repository-ha-operator-certified
      containers:
        - name: nexus-repository-ha-operator-certified
          # Replace this with the built image name
          image: {{operatorSHA}}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nexus-repository-ha-operator-certified"
            - name: RELATED_IMAGE_NEXUS
              value: {{certAppSHA}}
            - name: NEXUS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: nexus-repository-secret
                  key: nexusDatabaseUser
            - name: NEXUS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-repository-secret
                  key: nexusDatabasePassword
            - name: NEXUS_DB_JDBC_RL
              valueFrom:
                secretKeyRef:
                  name: nexus-repository-secret
                  key: nexusJdbcUrl
            - name: NEXUS_ADMIN_INITIAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexus-repository-secret
                  key: nexusInitialAdminPassword
            - name: NEXUS_POD_REPLICAS
              value: "2"
            - name: NEXUS_LICENSE_BASE_64
              valueFrom:
                secretKeyRef:
                  name: nexus-repository-secret
                  key: nexus-repo-license
            - name: NFS_PV_ENABLED
              value: "false"
            - name: LOCAL_PV_ENABLED
              value: "true"
            - name: NFS_PROVISIONER
              value: "nfs provisioner"
            - name: NFS_MOUNT_PATH
              value: "nfs mount path"
            - name: NFS_SERVER_IP
              value: "nfs server ip"
            - name: PVC_ACCESS_MODES
              value: "ReadWriteOnce"
            - name: CLUSTER_NODE_NAMES
              value: "minikube lima-rancher-desktop crc-87z92-master-0"
