# {{templateWarning}}
---
apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexusrepo-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nxrm-ha/values.yaml
  ingress:
    additionalRules: null
    annotations: null
    defaultRule: false
    dockerIngress:
      annotations: null
      enabled: false
      host: example.com
      name: nexus-docker-ingress
    dockerSubdomain: false
    enabled: false
    host: example.com
    name: nexus-ingress
    tls:
      enabled: false
      secretName: tlsSecretName
  license:
    fileContentsBase64: your_license_file_contents_in_base_64
    secretName: nexus-repo-license
  secret:
    nexusSecret:
      enabled: false
      name: nexus_secret.json
      nexusSecretsKeyId: "super_secret_key_id"
      secretKeyfileContentsBase64: "secretKeyfileContentsBase64" # secrets key file contents in base 64
      mountPath: /var/nexus-repo-secrets
  nexusData:
    volumeClaimTemplate:
      enabled: false
    pvc:
      accessMode: ReadWriteOnce
      size: 2Gi
    storageClass:
      name: nexusrepo-storage
      reclaimPolicy: Retain
      enabled: false
      volumeBindingMode: WaitForFirstConsumer
      provisioner: "provisioner"
      parameters: { }
  service:
    docker:
      enabled: false
      name: nexus-repo-docker-service
      port: 9090
      protocol: TCP
      targetPort: 8081
      type: NodePort
    nexus:
      enabled: false
      name: nexus-repo-service
      port: 80
      protocol: TCP
      targetPort: 8081
      type: NodePort
  statefulset:
    container:
      containerPort: 8081
      env:
        clustered: false
        install4jAddVmParams: -Xms2703m -Xmx2703m
        jdbcUrl: null
        nexusInitialPassword: nexusabc
        password: nexus
        user: nexus
        zeroDowntimeEnabled: false
      imageName: {{certAppSHA}}
      pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 4
          memory: 8Gi
        requests:
          cpu: 4
          memory: 8Gi
      terminationGracePeriod: 120
    imagePullSecrets: {}
    livenessProbe:
      failureThreshold: 6
      initialDelaySeconds: 240
      path: /
      periodSeconds: 60
    name: nexusrepo-statefulset
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 240
      path: /
      periodSeconds: 60
    replicaCount: 1
