# {{templateWarning}}
---
apiVersion: sonatype.com/v1alpha1
kind: NexusRepo
metadata:
  name: nexusrepo-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nxrm-ha/values.yaml
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    dockerIngress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: "false"
      name: nexus-docker-ingress
    dockerSubdomain: false
    enabled: "false"
    name: nexus-ingress
  license:
    fileContentsBase64: your_license_file_contents_in_base_64
    secretName: nexus-repo-license
  nexusData:
    local:
      accessMode: ReadWriteOnce
      enabled: "true"
      pv:
        matchNodes: example-node-1 example-node-2 example-node-3
        name: nexusrepo-local-storage-pv
        size: 200Gi
      storageClass:
        provisioner: kubernetes.io/no-provisioner
    nfs:
      accessMode: ReadWriteMany
      enabled: "false"
      pv:
        mountOptions:
          - hard
          - nfsvers=4.1
        mountPath: /nexusdata/mountPath
        name: nexusrepo-nfs-storage-pv
        server:
          ip: 70.71.156.85
        size: 200Gi
      storageClass:
        provisioner: nfs-provisioner
    pv:
      directoryPrefix: /var/nexus-repo-mgr-work-dir/work
    pvc:
      accessMode: ReadWriteOnce
      size: 100Gi
    storageClass:
      name: nexusrepo-storage
      reclaimPolicy: Retain
  route:
    enabled: "false"
  service:
    docker:
      enabled: "false"
      name: nexus-repo-docker-service
      port: 9090
      protocol: TCP
      targetPort: 8081
      type: NodePort
    nexus:
      enabled: "false"
      name: nexus-repo-service
      port: 80
      protocol: TCP
      targetPort: 8081
      type: NodePort
  statefulset:
    clusterName: nexusrepo-cluster
    container:
      containerPort: 8081
      env:
        clustered: true
        install4jAddVmParams: -Xms2703m -Xmx2703m
        jdbcUrl: jdbc:postgresql://your_database_server:5432/nexus
        nexusInitialPassword: nexusabc
        password: nexus
        user: nexus
      imageName: {{certAppSHA}}
      pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 4
          memory: 8Gi
        requests:
          cpu: 4
          memory: 8Gi
      terminationGracePeriod: 20
    name: nexusrepo-statefulset
    replicaCount: 2
