apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: nexus-repository-ha-operator-certified
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

  ##
  ## Rules for sonatype.com/v1alpha1, Kind: NexusRepo
  ##
- apiGroups:
  - sonatype.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
    - "*"
  apiGroups:
    - "storage.k8s.io"
  resources:
    - "storageclasses"
- verbs:
    - "*"
  apiGroups:
    - ""
  resources:
    - "persistentvolumes"
- verbs:
    - "*"
  apiGroups:
    - ""
  resources:
    - "secrets"
- verbs:
    - "*"
  apiGroups:
    - "apps"
  resources:
    - "statefulsets"

- apiGroups:
    - ""
  resources:
    - secrets
    - persistentvolumes
  verbs:
    - '*'
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - '*'
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - create
- apiGroups:
    - apps
  resourceNames:
    - nexus-repository-ha-operator-certified
  resources:
    - deployments/finalizers
  verbs:
    - update
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get