kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nexus-repository-ha-operator-certified
subjects:
- kind: ServiceAccount
  name: nexus-repository-ha-operator-certified
  namespace: nexus-repository-installation
roleRef:
  kind: ClusterRole
  name: nexus-repository-ha-operator-certified
  apiGroup: rbac.authorization.k8s.io
