apiVersion: v2
appVersion: 3.58.1
description: Highly available deployment of Sonatype Nexus Repository
home: https://www.sonatype.com/nexus-repository-oss
icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
- quickstart
- ci
- repository-manager
- nexus3
maintainers:
- name: Sonatype
name: nxrm-ha
type: application
version: 58.1.0
