apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Release.Name }}-{{ .Values.license.secretName }}
  namespace: "{{ .Values.namespaces.nexusNs }}"
type: Opaque
data:
  nexus-repo-license.lic: |-
    {{ $.Values.license.fileContentsBase64 }}
