{{- if $.Values.nexusData.local.enabled -}}
{{- if not $.Values.nexusData.nfs.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Release.Name }}-{{ .Values.workDir.configMapName }}
  namespace: {{ .Values.namespaces.nexusNs }}
data:
   create-nexus-work-dir.sh: |
    #!/bin/bash
    # Make Nexus Repository Manager work directory
    {{- range $value := until (.Values.statefulset.replicaCount | int )}}
    mkdir -p /nexus-repo-mgr-work-dir/work{{ $value }}
    {{- end }}
{{- end }}
{{- end }}