{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.name" . }}-conf
  labels:
{{ include "nexus.labels" . | nindent 4 }}
{{- if .Values.nexus.labels }}
{{ toYaml .Values.nexus.labels | nindent 4 }}
{{- end }}
data:
{{ toYaml .Values.config.data | nindent 2 }}
{{- end }}