{{- if .Values.statefulset.imagePullSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Values.statefulset.imagePullSecrets.name}}
data:
  .dockerconfigjson: {{ .Values.statefulset.imagePullSecrets.secret }}

type: kubernetes.io/dockerconfigjson
{{- end }}