{{- if .Values.statefulset.imagePullSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}
data:
  .dockerconfigjson: {{ .Values.statefulset.imagePullSecrets.secret }}

type: kubernetes.io/dockerconfigjson
{{- end }}