{{- if .Values.statefulset.imagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Values.statefulset.imagePullSecret.name}}
data:
  .dockerconfigjson: {{ .Values.statefulset.imagePullSecret.secret }}

type: kubernetes.io/dockerconfigjson
{{- end }}