{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Values.ingress.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Values.service.nexus.name }}
                port:
                  number: {{ .Values.service.nexus.port }}
    {{- if and .Values.ingress.host .Values.ingress.dockerSubdomain }}
    - host: "*.{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Values.service.nexus.name }}
                port:
                  number: {{ .Values.service.nexus.port }}
    {{- end }}
{{- end }}
---
{{- if .Values.ingress.dockerIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Values.ingress.dockerIngress.name }}
  {{- with .Values.ingress.dockerIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.ingress.dockerIngress.host }}
    - host: {{ .Values.ingress.dockerIngress.host }}
      http:
    {{- else}}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-{{ .Values.service.docker.name }}
                port:
                  number: {{ .Values.service.docker.port }}
{{- end }}
