{{- if .Values.secret.nexusSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Release.Name }}-{{ .Values.secret.nexusSecret.name }}
type: Opaque
data:
  {{ .Values.secret.nexusSecret.name }}: |-
   {{ .Values.secret.nexusSecret.secretKeyfileContentsBase64 }}
{{- end }}
