{{- if .Values.statefulset.container.env.clustered }}
{{- range $value := until (.Values.statefulset.replicaCount | int )}}
{{- if and $.Values.nexusData.local.enabled ( not $.Values.nexusData.nfs.enabled ) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.nexusData.local.pv.name }}-{{ $value }}
spec:
  capacity:
    storage: {{ $.Values.nexusData.local.pv.size }}
  volumeMode: Filesystem
  accessModes:
  - {{ $.Values.nexusData.local.accessMode }}
  persistentVolumeReclaimPolicy: {{ $.Values.nexusData.storageClass.reclaimPolicy }}
  storageClassName: {{ $.Chart.Name }}-{{ $.Chart.Version}}-{{ $.Values.nexusData.storageClass.name }}
  local:
    path: {{ $.Values.nexusData.pv.directoryPrefix}}{{ $value }}
  {{- with (splitList " " $.Values.nexusData.local.pv.matchNodes) }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                {{- toYaml . | nindent 16 }}
  {{- end }}
{{- end }}
---
{{- if and $.Values.nexusData.nfs.enabled (not $.Values.nexusData.local.enabled ) }}
{{- $serverPaths := (splitList " " $.Values.nexusData.nfs.pv.exportedServerPaths) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Values.nexusData.nfs.pv.name }}-{{ $value }}
spec:
  capacity:
    storage: {{ $.Values.nexusData.nfs.pv.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ $.Values.nexusData.nfs.accessMode }}
  persistentVolumeReclaimPolicy: {{ $.Values.nexusData.storageClass.reclaimPolicy }}
  storageClassName: {{ $.Chart.Name }}-{{ $.Chart.Version}}-{{ $.Values.nexusData.storageClass.name }}
  {{- with $.Values.nexusData.nfs.pv.mountOptions }}
  mountOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  nfs:
    path: {{ index $serverPaths $value }}
    server: {{ $.Values.nexusData.nfs.pv.server.ip }}
{{- end }}
{{- end }}
{{- end }}
