{{- if .Values.service.nexus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Chart.Name }}-{{ .Values.service.nexus.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    app: nxrm
spec:
  type: {{ .Values.service.nexus.type }}
  selector:
    app: nxrm
  ports:
    - protocol: {{ .Values.service.nexus.protocol }}
      port: {{ .Values.service.nexus.port }}
      targetPort: {{ .Values.service.nexus.targetPort }}
{{- end }}
---
{{- if .Values.service.docker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service.docker.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
    app: nxrm
spec:
  type: {{ .Values.service.docker.type }}
  selector:
    app: nxrm
  ports:
    - protocol: {{ .Values.service.docker.protocol }}
      port: {{ .Values.service.docker.port }}
      targetPort: {{ .Values.service.docker.targetPort }}
{{- end }}

