# For local: we create a storage class below based on Kubernetes recommendation: https://kubernetes.io/docs/concepts/storage/storage-classes/#local
# In addition, having this storage class allows us to do automatic creation of persistent volume claims based on the
# pre created persistent volume objects. See statefulset's volumeClaimTemplates for 'nexusdata' volume for how we use this.
{{- if and (eq $.Values.nexusData.local.enabled "true") (not ( eq $.Values.nexusData.nfs.enabled "true" )) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Values.nexusData.storageClass.name}}
provisioner: {{ .Values.nexusData.local.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.nexusData.storageClass.reclaimPolicy }}
{{- end }}
---
{{- if and (eq $.Values.nexusData.nfs.enabled "true") (not (eq $.Values.nexusData.local.enabled "true")) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version}}-{{ .Values.nexusData.storageClass.name}}
provisioner: {{ .Values.nexusData.nfs.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.nexusData.storageClass.reclaimPolicy }}
{{- end -}}